version: "3.7"


services:
  backend:
    volumes:
      - static:/static
      - ./backend:/app
    env_file: ./backend/.env
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
      
  db:
    image: postgres:15.5-alpine3.19
    container_name: tracker_db
    restart: always
    env_file: ./backend/.env
    command: -p 5432
    volumes:
        - ./backend/pgdata:/var/lib/postgresql/data
    expose:
        - 5432
  
  frontend:
    build:
      context: ./frontend
    command: sh -c "npm install -g serve && serve -s build"
    volumes:
      - frontend:/app/build
    depends_on:
      - backend
  
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:

      



