version: '3.7'

services:
  backend:
    build: ./backend
    container_name: "backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    networks:
      - dev
    depends_on:
      - db
    env_file:
      - ./backend/.env
    # stdin_open: true
    # tty: true

  frontend:
    build: ./frontend
    container_name: "frontend"
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
    networks:
      - dev
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - "backend"
    command:
      npm start

  db:
    image: postgres:13.2-alpine
    container_name: "tracker_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
  node-modules:

networks:
  dev: