version: "3.7"
services:
  backend:
    build:
      context: ./backend
    env_file: ./backend/.env
    container_name: tracker_backend
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:15.5-alpine3.19
    container_name: tracker_db
    restart: always
    env_file: ./backend/.env
    command: -p 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    

