# Generated by Django 4.2 on 2024-06-02 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0006_alter_offer_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-click_on']},
        ),
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
