# Generated by Django 4.2 on 2024-05-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='action',
            field=models.CharField(choices=[('CAMPAIGN_LIST', 'Campaign List'), ('CAMPAIGN_DETAIL', 'Campaign Detail'), ('OFFER_LIST', 'Offer List'), ('OFFER_DETAIL', 'Offer Detail')], default='CAMPAIGN_LIST'),
        ),
        migrations.AddField(
            model_name='click',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackers.campaign'),
        ),
        migrations.AlterField(
            model_name='click',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackers.offer'),
        ),
    ]
