# Generated by Django 4.2 on 2024-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_click_action_click_campaign_alter_click_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='os',
            field=models.CharField(null=True),
        ),
    ]
