# Generated by Django 4.2 on 2024-05-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_lead_os'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
    ]
